[package]
name = "Reco-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.78.2"
anyhow = "1.0.70"
reqwest = { version = "0.11.16", features = ["blocking"] }
